version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      # instalar libs necessárias para o Cypress
      - yum install -y libX11 libXScrnSaver libXtst libXrandr libXcursor libXdamage libXfixes mesa-libGL alsa-lib
  build:
    commands:
      - echo Running Cypress tests...
      - npx cypress run
artifacts:
  files:
    - '**/*'

